project_id: opencast-community
api_token_env: CROWDIN_TOKEN
base_path: .
preserve_hierarchy: true

files:
  - source: '/app/src/org/opencastproject/adminui/languages/lang-en_US.json'
    translation: '/app/src/org/opencastproject/adminui/languages/lang-%locale_with_underscore%.json'