on:
  push:
    tags:
    - '*-*-*'

name: Create release draft 

jobs:
  build:
    name: Create release from tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: get node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: download dependencies
        run: npm ci
        working-directory: ./app

      - name: create release tarball
        run: ../.github/build-release.sh
        working-directory: ./app

      - name: create new release
        uses: softprops/action-gh-release@v2
        with:
          files: ./app/oc-admin-ui-*.tar.gz
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
